"use client";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Quote, Lightbulb } from "lucide-react";
import { AnimatePresence } from "framer-motion";

const quotesEN = [
  { text: "The goal of a successful trader is to make the best trades, not all the trades.", type: "Discipline" },
  { text: "Amateurs hope. Professionals plan.", type: "Mindset" },
  { text: "Stick to your trading plan every single day.", type: "Discipline" },
  { text: "Patience is your best trading friend.", type: "Patience" },
  { text: "Control your emotions or they will control your account.", type: "Psychology" },
  { text: "Small consistent profits beat big risky wins.", type: "Mindset" },
  { text: "A good trader always protects their capital first.", type: "Risk" },
  { text: "Losses are lessons, not failures.", type: "Psychology" },
  { text: "Trade what you see, not what you hope.", type: "Discipline" },
  { text: "The market is always right. Respect it.", type: "Mindset" },
  { text: "Wait for the perfect setup. Good things come to patient traders.", type: "Patience" },
  { text: "Never revenge trade after a loss.", type: "Psychology" },
  { text: "Discipline makes the difference between winners and losers.", type: "Discipline" },
  { text: "Focus on process, not on daily profits.", type: "Mindset" },
  { text: "Risk only what you can afford to lose.", type: "Risk" },
  { text: "Fear and greed destroy more accounts than bad trades.", type: "Psychology" },
  { text: "One good trade follows many patient waits.", type: "Patience" },
  { text: "Cut your losses quickly. Let your winners run.", type: "Discipline" },
  { text: "Trading is 80% psychology and 20% strategy.", type: "Psychology" },
  { text: "A calm mind makes better trading decisions.", type: "Mindset" },
  { text: "Follow your rules even when it feels boring.", type: "Discipline" },
  { text: "Every master trader was once a beginner.", type: "Mindset" },
  { text: "Take small risks until you prove yourself.", type: "Risk" },
  { text: "The best trade is often no trade.", type: "Patience" },
  { text: "Learn from every trade, win or lose.", type: "Psychology" },
  { text: "Consistency beats occasional big wins.", type: "Mindset" },
  { text: "Never trade with money you need for bills.", type: "Risk" },
  { text: "Stay humble after wins and strong after losses.", type: "Psychology" },
  { text: "Trust your plan more than your feelings.", type: "Discipline" },
  { text: "Markets reward patient and prepared traders.", type: "Patience" },
  { text: "Avoid trading when you feel angry or excited.", type: "Psychology" },
  { text: "Build your account slowly but surely.", type: "Mindset" },
  { text: "One bad day should not destroy your week.", type: "Risk" },
  { text: "Review your trades weekly to improve.", type: "Discipline" },
  { text: "Success comes from daily small improvements.", type: "Mindset" },
  { text: "The market will always give new opportunities.", type: "Patience" },
  { text: "Protect your profits like you protect your capital.", type: "Risk" },
  { text: "A losing streak ends when you follow your rules.", type: "Psychology" },
  { text: "Trade less, win more.", type: "Discipline" },
  { text: "Your mindset decides your trading results.", type: "Mindset" },
  { text: "Never chase the price. Let it come to you.", type: "Patience" },
  { text: "Emotions are expensive in trading.", type: "Psychology" },
  { text: "Size your position according to your confidence.", type: "Risk" },
  { text: "Great traders love the process, not just money.", type: "Mindset" },
  { text: "Journal every trade to see your mistakes.", type: "Discipline" },
  { text: "Stay out when the market is unclear.", type: "Patience" },
  { text: "Accept losses as part of the trading game.", type: "Psychology" },
  { text: "Discipline turns average traders into great ones.", type: "Discipline" },
  { text: "Focus on what you can control - your rules.", type: "Mindset" },
  { text: "Big accounts are built one good trade at a time.", type: "Patience" },
  { text: "Greed makes you enter bad trades.", type: "Psychology" },
  { text: "Always know your stop loss before you enter.", type: "Risk" },
  { text: "Trading is a marathon, not a sprint.", type: "Mindset" },
  { text: "The best traders are boringly consistent.", type: "Discipline" },
  { text: "Wait for confirmation before you trade.", type: "Patience" },
  { text: "Fear makes you exit winners too early.", type: "Psychology" },
  { text: "Never risk more than 1-2% on a single trade.", type: "Risk" },
  { text: "Learn to love waiting for the right moment.", type: "Patience" },
  { text: "Your trading edge comes from following rules.", type: "Discipline" },
  { text: "Stay positive even after losing days.", type: "Mindset" },
  { text: "Overtrading is the fastest way to lose money.", type: "Psychology" },
  { text: "Master yourself before you master the market.", type: "Psychology" },
  { text: "Simple rules followed strictly win in the long run.", type: "Discipline" },
  { text: "The market pays those who respect it.", type: "Mindset" },
  { text: "Take breaks when trading feels stressful.", type: "Psychology" },
  { text: "Position size is more important than entry.", type: "Risk" },
  { text: "Dream big but trade small.", type: "Mindset" },
  { text: "Patience turns good traders into legends.", type: "Patience" },
  { text: "Do not trade to prove you are right.", type: "Psychology" },
  { text: "A plan without discipline is just a wish.", type: "Discipline" },
  { text: "Winners focus on probabilities, not certainties.", type: "Mindset" },
  { text: "Losses teach more than wins if you listen.", type: "Psychology" },
  { text: "Trade with clarity, not with hope.", type: "Discipline" },
  { text: "Time in the market is not as important as timing.", type: "Patience" },
  { text: "Control risk and the profits take care of themselves.", type: "Risk" },
  { text: "Stay disciplined when everyone else is excited.", type: "Discipline" },
  { text: "Trading success is built on habits.", type: "Mindset" },
  { text: "Never move your stop loss to give a trade more room.", type: "Discipline" },
  { text: "A quiet mind sees the market clearly.", type: "Psychology" },
  { text: "Small daily wins create big yearly results.", type: "Mindset" },
  { text: "The best traders take days off.", type: "Psychology" },
  { text: "Respect every trade with proper risk.", type: "Risk" },
  { text: "Hope is not a trading strategy.", type: "Mindset" },
  { text: "Discipline is choosing what you want most over what you want now.", type: "Discipline" },
  { text: "Wait calmly. The setup will come.", type: "Patience" },
  { text: "Your account grows when you stop making stupid mistakes.", type: "Psychology" },
  { text: "Trade the market you see, not the one you want.", type: "Mindset" },
  { text: "One rule broken can cost many good trades.", type: "Discipline" },
  { text: "Successful traders are not smarter, they are more disciplined.", type: "Discipline" },
  { text: "Let the trade come to you.", type: "Patience" },
  { text: "Emotions have no place in your trading decisions.", type: "Psychology" },
  { text: "Build slowly. Protect always.", type: "Risk" },
  { text: "Every professional started as a beginner who did not quit.", type: "Mindset" },
  { text: "Follow your checklist before every trade.", type: "Discipline" },
  { text: "The market is full of opportunities every week.", type: "Patience" },
  { text: "Pride loses money. Humility makes money.", type: "Psychology" },
  { text: "Risk management is the real trading skill.", type: "Risk" },
  { text: "Stay consistent even when results are slow.", type: "Mindset" },
  { text: "A stopped out trade is better than a big loss.", type: "Discipline" },
  { text: "Good traders love rules more than money.", type: "Psychology" },
  { text: "Do not check your account every minute.", type: "Psychology" },
  { text: "The best revenge is a profitable account.", type: "Mindset" },
  { text: "Patience is power in trading.", type: "Patience" },
  { text: "Stick to high probability setups only.", type: "Discipline" },
  { text: "Trading is simple but not easy.", type: "Mindset" },
  { text: "Control what you can. Ignore the rest.", type: "Psychology" },
  { text: "Never average down a losing trade.", type: "Risk" },
  { text: "Winners keep learning every day.", type: "Mindset" },
  { text: "A clear plan removes fear.", type: "Discipline" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", type: "Patience" },
  { text: "Feelings lie. Charts tell the truth.", type: "Psychology" },
  { text: "Size matters - keep it small when unsure.", type: "Risk" },
  { text: "Discipline today creates freedom tomorrow.", type: "Discipline" },
  { text: "Great traders focus on survival first.", type: "Mindset" },
  { text: "Take your profit when the plan says so.", type: "Discipline" },
  { text: "Losing is part of winning in trading.", type: "Psychology" },
  { text: "Wait for your edge before you risk money.", type: "Patience" },
  { text: "A trading journal is your best teacher.", type: "Mindset" },
  { text: "Never let one trade decide your day.", type: "Psychology" },
  { text: "Consistent small gains compound into wealth.", type: "Mindset" },
  { text: "Rules protect you from yourself.", type: "Discipline" },
  { text: "The market does not care about your opinion.", type: "Mindset" },
  { text: "Breathe before you click buy or sell.", type: "Psychology" },
  { text: "Risk little. Learn much.", type: "Risk" },
  { text: "Trading success starts with self-control.", type: "Discipline" },
  { text: "Be early to prepare, late to trade.", type: "Patience" },
  { text: "Winners cut losers fast.", type: "Discipline" },
  { text: "Your next trade should be your best trade.", type: "Mindset" },
  { text: "Do not trade for excitement.", type: "Psychology" },
  { text: "A safe small profit is better than a risky big one.", type: "Risk" },
  { text: "Stay calm in chaos.", type: "Psychology" },
  { text: "Discipline is freedom in trading.", type: "Discipline" },
  { text: "Markets change. Your rules should not.", type: "Mindset" },
  { text: "The patient trader eats the impatient trader's lunch.", type: "Patience" },
  { text: "Review losses without emotion.", type: "Psychology" },
  { text: "Trade with logic, not with ego.", type: "Mindset" },
  { text: "Stop loss is your insurance policy.", type: "Risk" },
  { text: "Small position, big peace of mind.", type: "Risk" },
  { text: "Every day is a chance to follow your plan.", type: "Discipline" },
  { text: "Trading is a skill. Practice it daily.", type: "Mindset" },
  { text: "Ignore hot tips. Trust your analysis.", type: "Discipline" },
  { text: "The best traders are the most patient ones.", type: "Patience" },
  { text: "Do not fight the trend.", type: "Mindset" },
  { text: "Your account thanks you for good risk management.", type: "Risk" },
  { text: "Stay objective. Remove emotions.", type: "Psychology" },
  { text: "One percent better every day leads to big success.", type: "Mindset" },
  { text: "No plan = gambling.", type: "Discipline" },
  { text: "Celebrate sticking to rules, not just profits.", type: "Psychology" },
  { text: "The market gives and takes. Be ready for both.", type: "Mindset" },
  { text: "Sit on your hands when unsure.", type: "Patience" },
  { text: "Good traders lose small. Bad traders lose big.", type: "Risk" },
  { text: "Discipline separates dreamers from doers.", type: "Discipline" },
  { text: "Trade to make money, not to be right.", type: "Psychology" },
  { text: "Keep it simple. Simple works.", type: "Mindset" },
  { text: "Never trade when tired or distracted.", type: "Psychology" },
  { text: "Build confidence with small wins.", type: "Mindset" },
  { text: "A rule is only powerful when you follow it.", type: "Discipline" },
  { text: "Time is your friend when you are patient.", type: "Patience" },
  { text: "Risk wisely. Sleep peacefully.", type: "Risk" },
  { text: "The best trade you never took is sometimes the best.", type: "Discipline" },
  { text: "Master your mind and you master trading.", type: "Psychology" },
  { text: "Focus on today’s trade only.", type: "Mindset" },
  { text: "Patience prevents painful losses.", type: "Patience" },
  { text: "Follow the plan like your life depends on it.", type: "Discipline" },
  { text: "Losses are tuition fees for learning.", type: "Psychology" },
  { text: "Consistent action creates consistent results.", type: "Mindset" },
  { text: "Do not put all eggs in one trade.", type: "Risk" },
  { text: "A disciplined trader is a dangerous trader.", type: "Discipline" },
  { text: "The market is always teaching. Are you listening?", type: "Mindset" },
  { text: "Wait. Watch. Then act.", type: "Patience" },
  { text: "Emotions make you average. Discipline makes you great.", type: "Psychology" },
  { text: "Protect capital like it is your only chance.", type: "Risk" },
  { text: "Trading is 90% waiting and 10% acting.", type: "Patience" },
  { text: "Stay in the game long enough to win.", type: "Mindset" },
  { text: "Rules are your edge over amateurs.", type: "Discipline" },
  { text: "Take responsibility for every trade.", type: "Psychology" },
  { text: "Slow and steady wins the trading race.", type: "Mindset" },
  { text: "Never increase risk after a loss.", type: "Risk" },
  { text: "A calm trader sees more opportunities.", type: "Psychology" },
  { text: "Discipline is daily practice.", type: "Discipline" },
  { text: "Trade with confidence, not with arrogance.", type: "Mindset" },
  { text: "The setup must be perfect before you enter.", type: "Patience" },
  { text: "Your biggest enemy in trading is yourself.", type: "Psychology" },
  { text: "Small risks repeated create big rewards.", type: "Risk" },
  { text: "Plan the trade. Trade the plan.", type: "Discipline" },
  { text: "Good traders are not lucky. They are prepared.", type: "Mindset" },
  { text: "Breathe out fear. Breathe in discipline.", type: "Psychology" },
  { text: "Respect the market. It has been here longer than you.", type: "Mindset" },
  { text: "Patience is the secret weapon of rich traders.", type: "Patience" },
  { text: "Never trade just because you are bored.", type: "Psychology" },
  { text: "Risk less when you are not sure.", type: "Risk" },
  { text: "Every winning trader has lost many times.", type: "Mindset" },
  { text: "Discipline turns trading dreams into reality.", type: "Discipline" },
  { text: "Watch the chart, not your emotions.", type: "Psychology" },
  { text: "The best traders take the best setups only.", type: "Discipline" },
  { text: "Stay hungry for knowledge but patient in execution.", type: "Mindset" },
  { text: "A good stop loss saves your account.", type: "Risk" },
  { text: "Trading is a business. Treat it like one.", type: "Mindset" },
  { text: "Wait for the trend to confirm.", type: "Patience" },
  { text: "Control your size. Control your emotions.", type: "Psychology" },
  { text: "Consistency is the real holy grail.", type: "Mindset" },
  { text: "Follow rules when it is hardest - that is when it matters.", type: "Discipline" },
  { text: "Markets reward those who wait.", type: "Patience" },
  { text: "Learn to sit. Learn to stand aside.", type: "Psychology" },
  { text: "Never revenge trade. Walk away instead.", type: "Psychology" },
  { text: "Your edge is in your discipline.", type: "Discipline" },
  { text: "Think in probabilities, not in hopes.", type: "Mindset" },
  { text: "A small loss is a good loss.", type: "Risk" },
  { text: "Trade like a machine, think like a human.", type: "Psychology" },
  { text: "The longer you wait, the better the reward.", type: "Patience" },
  { text: "Discipline over motivation every day.", type: "Discipline" },
  { text: "Winners keep their losses tiny.", type: "Risk" },
  { text: "Stay focused on long term success.", type: "Mindset" },
  { text: "Do not let one win make you overconfident.", type: "Psychology" },
  { text: "Simple and disciplined beats complex and emotional.", type: "Mindset" },
  { text: "The market is open every day. No need to rush.", type: "Patience" },
  { text: "Your trading plan is your boss.", type: "Discipline" },
  { text: "Accept what the market gives you.", type: "Psychology" },
  { text: "Risk management is self love.", type: "Risk" },
  { text: "Great things take time in trading.", type: "Patience" },
  { text: "Be a student of the market forever.", type: "Mindset" },
  { text: "Stick to your system through good and bad times.", type: "Discipline" },
  { text: "Emotions are the biggest trading cost.", type: "Psychology" },
  { text: "Trade small until you are consistent.", type: "Risk" },
  { text: "The quiet traders make the most money.", type: "Mindset" },
  { text: "Patience is profitable.", type: "Patience" },
  { text: "A broken rule today means bigger problems tomorrow.", type: "Discipline" },
  { text: "Do not trade the news. Trade the chart.", type: "Mindset" },
  { text: "Stay cool when others panic.", type: "Psychology" },
  { text: "One good habit repeated daily changes everything.", type: "Mindset" },
  { text: "Your stop loss is non-negotiable.", type: "Risk" },
  { text: "Trading is about making better decisions than yesterday.", type: "Psychology" },
  { text: "Discipline is the bridge between goals and success.", type: "Discipline" },
  { text: "The best traders lose with grace.", type: "Psychology" },
  { text: "Wait for clarity before you risk money.", type: "Patience" },
  { text: "Focus on return per risk, not just return.", type: "Risk" },
  { text: "Keep learning. Keep improving. Keep winning.", type: "Mindset" },
  { text: "No emotions. Just execution.", type: "Discipline" },
  { text: "The market will wait for you.", type: "Patience" },
  { text: "Small consistent effort beats occasional big effort.", type: "Mindset" },
  { text: "Protect your capital like a mother protects her child.", type: "Risk" },
  { text: "You win by not losing big.", type: "Psychology" },
  { text: "Trade only when everything lines up.", type: "Discipline" },
  { text: "Success in trading is a long game.", type: "Mindset" },
  { text: "Fear is normal. Acting on fear is expensive.", type: "Psychology" },
  { text: "Discipline today. Wealth tomorrow.", type: "Discipline" },
  { text: "The patient trader always has the last laugh.", type: "Patience" },
  { text: "Review. Learn. Improve. Repeat.", type: "Mindset" },
  { text: "Never bet the farm on one trade.", type: "Risk" },
  { text: "A good trader is a calm trader.", type: "Psychology" },
  { text: "Follow the rules. Collect the profits.", type: "Discipline" },
  { text: "Trading rewards those who respect risk.", type: "Risk" },
  { text: "Stay humble. Stay hungry. Stay disciplined.", type: "Mindset" },
  { text: "The best setup is worth the wait.", type: "Patience" },
  { text: "Your mind is your most powerful trading tool.", type: "Psychology" },
  { text: "Consistency is king in trading.", type: "Mindset" },
  { text: "Cut losses. Ride winners. Repeat.", type: "Discipline" },
  { text: "Do not force trades. Let them happen.", type: "Patience" },
  { text: "Trading is simple: follow rules and manage risk.", type: "Mindset" },
  { text: "A disciplined mind cannot be defeated.", type: "Psychology" },
  { text: "Risk smart. Trade smart. Win smart.", type: "Risk" },
  { text: "Every day you follow your plan is a winning day.", type: "Discipline" },
  { text: "The market is patient. You should be too.", type: "Patience" },
  { text: "Winners focus on what is right, not who is right.", type: "Mindset" },
  { text: "Stay in control at all times.", type: "Psychology" },
  { text: "Discipline is the foundation of all trading success.", type: "Discipline" },
  { text: "Trade less. Study more. Earn more.", type: "Mindset" },
  { text: "Never let hope replace your stop loss.", type: "Risk" },
  { text: "A calm mind sees the best trades.", type: "Psychology" },
  { text: "Build your trading muscle with patience.", type: "Patience" },
  { text: "The road to profitable trading is paved with discipline.", type: "Discipline" },
  { text: "Trust the process. Trust yourself.", type: "Mindset" },
  { text: "Good risk management = long trading career.", type: "Risk" },
  { text: "Embrace the wait. It pays well.", type: "Patience" },
  { text: "Trading psychology is the real game.", type: "Psychology" },
  { text: "Discipline turns beginners into professionals.", type: "Discipline" },
  { text: "The best traders are the most boring ones.", type: "Mindset" },
  { text: "Control risk. Let profits surprise you.", type: "Risk" },
  { text: "Stay present. Trade the now.", type: "Psychology" },
  { text: "Patience is your silent profit partner.", type: "Patience" },
  { text: "Follow rules today for bigger account tomorrow.", type: "Discipline" },
  { text: "Trading is a test of character.", type: "Mindset" },
  { text: "Never trade angry. Never trade desperate.", type: "Psychology" },
  { text: "Small position sizes keep you in the game.", type: "Risk" },
  { text: "The disciplined trader always comes back stronger.", type: "Discipline" },
  { text: "Markets move. Your rules stay.", type: "Mindset" },
  { text: "Wait like a hunter. Strike like a pro.", type: "Patience" },
  { text: "Your trading journal never lies.", type: "Psychology" },
  { text: "Discipline is choosing long term success over short term fun.", type: "Discipline" },
  { text: "Be selective. Be profitable.", type: "Mindset" },
  { text: "Risk only 1%. Sleep like a baby.", type: "Risk" },
  { text: "A patient trader is a wealthy trader.", type: "Patience" },
  { text: "Master your emotions. Master the market.", type: "Psychology" },
  { text: "Every rule followed is money earned.", type: "Discipline" },
  { text: "Trading success belongs to the consistent.", type: "Mindset" },
  { text: "Stand aside when the market is not clear.", type: "Patience" },
  { text: "Protect your capital. Everything else follows.", type: "Risk" },
  { text: "The best traders lose well.", type: "Psychology" },
  { text: "Discipline is your superpower.", type: "Discipline" },
  { text: "Think long term. Trade short term.", type: "Mindset" },
  { text: "Patience pays dividends in trading.", type: "Patience" },
  { text: "Control yourself. Control your results.", type: "Psychology" },
  { text: "A good trader is patient, disciplined, and calm.", type: "Mindset" },
  { text: "Rules first. Profits second.", type: "Discipline" },
  { text: "Never chase. Always plan.", type: "Mindset" },
  { text: "The market is generous to the disciplined.", type: "Discipline" },
  { text: "Stay calm and follow your plan.", type: "Psychology" },
  { text: "Small risks. Big patience. Great rewards.", type: "Patience" },
  { text: "Trading is easy when you remove emotions.", type: "Psychology" },
  { text: "Discipline today. Celebrate tomorrow.", type: "Discipline" },
  { text: "The patient always win in the end.", type: "Patience" },
  { text: "Your best days are ahead if you stay disciplined.", type: "Mindset" },
  { text: "Risk smart. Trade calm. Win big.", type: "Risk" },
  { text: "Follow the plan. Trust the process.", type: "Discipline" }
];

const quotesHN = [
    { text: "Ek successful trader ka goal best trades lena hota hai, sab trades nahi.", type: "Discipline" },
  { text: "Amateurs umeed karte hain. Professionals plan banate hain.", type: "Mindset" },
  { text: "Apne trading plan ko har din follow karo.", type: "Discipline" },
  { text: "Patience tumhara sabse achha trading friend hai.", type: "Patience" },
  { text: "Apne emotions ko control karo, warna woh tumhare account ko control karenge.", type: "Psychology" },
  { text: "Chhote aur consistent profits, bade risky wins se better hote hain.", type: "Mindset" },
  { text: "Ek achha trader hamesha pehle apni capital ko protect karta hai.", type: "Risk" },
  { text: "Losses lessons hote hain, failures nahi.", type: "Psychology" },
  { text: "Woh trade karo jo dikh raha hai, na ki jo tum hope kar rahe ho.", type: "Discipline" },
  { text: "Market hamesha right hota hai. Uska respect karo.", type: "Mindset" },
  { text: "Perfect setup ka wait karo. Achhi cheezein patient traders ko milti hain.", type: "Patience" },
  { text: "Loss ke baad kabhi revenge trade mat karo.", type: "Psychology" },
  { text: "Discipline winners aur losers ke beech ka difference banati hai.", type: "Discipline" },
  { text: "Daily profits par nahi, process par focus karo.", type: "Mindset" },
  { text: "Sirf utna hi risk lo jitna tum lose kar sakte ho.", type: "Risk" },
  { text: "Fear aur greed bad trades se zyada accounts destroy karte hain.", type: "Psychology" },
  { text: "Ek achhi trade ke pehle bahut saare patient waits hote hain.", type: "Patience" },
  { text: "Apne losses jaldi cut karo. Apne winners ko run karne do.", type: "Discipline" },
  { text: "Trading 80% psychology aur 20% strategy hoti hai.", type: "Psychology" },
  { text: "Calm mind better trading decisions leta hai.", type: "Mindset" },
  { text: "Boring lagne par bhi apne rules follow karo.", type: "Discipline" },
  { text: "Har master trader kabhi beginner tha.", type: "Mindset" },
  { text: "Jab tak tum khud ko prove na kar lo, small risks lo.", type: "Risk" },
  { text: "Best trade aksar no trade hota hai.", type: "Patience" },
  { text: "Har trade se seekho, chahe win ho ya lose.", type: "Psychology" },
  { text: "Consistency occasional big wins se better hoti hai.", type: "Mindset" },
  { text: "Bills ke paise se kabhi trade mat karo.", type: "Risk" },
  { text: "Win ke baad humble raho aur loss ke baad strong raho.", type: "Psychology" },
  { text: "Apne feelings se zyada apne plan par trust karo.", type: "Discipline" },
  { text: "Markets patient aur prepared traders ko reward karte hain.", type: "Patience" },
  { text: "Jab tumhe gussa ya excitement ho, tab trading avoid karo.", type: "Psychology" },
  { text: "Apna account dheere lekin sure tareeke se build karo.", type: "Mindset" },
  { text: "Ek bura din tumhara poora week destroy nahi karna chahiye.", type: "Risk" },
  { text: "Apni trades ko weekly review karo taaki improve kar sako.", type: "Discipline" },
  { text: "Success daily chhoti improvements se aati hai.", type: "Mindset" },
  { text: "Market hamesha naye opportunities dega.", type: "Patience" },
  { text: "Apne profits ko bhi utni hi care se protect karo jitni capital ko karte ho.", type: "Risk" },
  { text: "Losing streak tab khatam hoti hai jab tum apne rules follow karte ho.", type: "Psychology" },
  { text: "Kam trade karo, zyada jeeto.", type: "Discipline" },
  { text: "Tumhara mindset hi tumhare trading results decide karta hai.", type: "Mindset" },
  { text: "Price ko chase mat karo. Use tumhare paas aane do.", type: "Patience" },
  { text: "Trading me emotions expensive hote hain.", type: "Psychology" },
  { text: "Apni confidence ke hisaab se position size rakho.", type: "Risk" },
  { text: "Great traders money se zyada process ko love karte hain.", type: "Mindset" },
  { text: "Har trade ko journal karo taaki apni mistakes dekh sako.", type: "Discipline" },
  { text: "Jab market clear na ho, tab bahar raho.", type: "Patience" },
  { text: "Losses ko trading game ka hissa accept karo.", type: "Psychology" },
  { text: "Discipline average traders ko great traders me badal deti hai.", type: "Discipline" },
  { text: "Jo control kar sakte ho usi par focus karo - apne rules par.", type: "Mindset" },
  { text: "Bade accounts ek-ek achhi trade se bante hain.", type: "Patience" },
  { text: "Greed tumhe bad trades me enter karwati hai.", type: "Psychology" },
  { text: "Enter karne se pehle hamesha stop loss pata hona chahiye.", type: "Risk" },
  { text: "Trading ek marathon hai, sprint nahi.", type: "Mindset" },
  { text: "Best traders boringly consistent hote hain.", type: "Discipline" },
  { text: "Trade karne se pehle confirmation ka wait karo.", type: "Patience" },
  { text: "Fear winners ko jaldi exit karwa deta hai.", type: "Psychology" },
  { text: "Ek single trade par kabhi 1-2% se zyada risk mat lo.", type: "Risk" },
  { text: "Right moment ka wait karna seekho aur enjoy karo.", type: "Patience" },
  { text: "Tumhara trading edge rules follow karne se aata hai.", type: "Discipline" },
  { text: "Losing days ke baad bhi positive raho.", type: "Mindset" },
  { text: "Overtrading paise lose karne ka fastest way hai.", type: "Psychology" },
  { text: "Khud ko master karo, phir market ko.", type: "Psychology" },
  { text: "Simple rules ko strictly follow karna long run me jeet dilata hai.", type: "Discipline" },
  { text: "Market unko reward karta hai jo uska respect karte hain.", type: "Mindset" },
  { text: "Trading stressful lage to break le lo.", type: "Psychology" },
  { text: "Position size entry se zyada important hoti hai.", type: "Risk" },
  { text: "Bade sapne dekho, par trade chhota karo.", type: "Mindset" },
  { text: "Sabr good traders ko legends bana deta hai.", type: "Patience" },
  { text: "Sirf prove karne ke liye trade mat karo ki tum right ho.", type: "Psychology" },
  { text: "Plan bina discipline ke bas ek wish hota hai.", type: "Discipline" },
  { text: "Winners certainty nahi, probabilities par focus karte hain.", type: "Mindset" },
  { text: "Losses wins se zyada sikhate hain agar tum dhyan do.", type: "Psychology" },
  { text: "Clarity ke saath trade karo, hope ke saath nahi.", type: "Discipline" },
  { text: "Market me time rehna timing jitna important nahi hota.", type: "Patience" },
  { text: "Risk control karo, profits apne aap sambhal jaayenge.", type: "Risk" },
  { text: "Jab sab excited hon, tab bhi disciplined raho.", type: "Discipline" },
  { text: "Trading success habits par build hoti hai.", type: "Mindset" },
  { text: "Kabhi bhi stop loss ko zyada room dene ke liye move mat karo.", type: "Discipline" },
  { text: "Quiet mind market ko clearly dekhta hai.", type: "Psychology" },
  { text: "Chhoti daily wins bade yearly results banati hain.", type: "Mindset" },
  { text: "Best traders days off bhi lete hain.", type: "Psychology" },
  { text: "Har trade ko proper risk ke saath respect do.", type: "Risk" },
  { text: "Hope trading strategy nahi hai.", type: "Mindset" },
  { text: "Discipline ka matlab hai jo tum ab chahte ho usse zyada important cheez choose karna.", type: "Discipline" },
  { text: "Calm raho. Setup aayega.", type: "Patience" },
  { text: "Jab tum stupid mistakes karna band karte ho, tab tumhara account grow karta hai.", type: "Psychology" },
  { text: "Jo market dikh raha hai usko trade karo, jo tum chahte ho usko nahi.", type: "Mindset" },
  { text: "Ek rule todna bahut saare achhe trades ki cost ban sakta hai.", type: "Discipline" },
  { text: "Successful traders zyada smart nahi, zyada disciplined hote hain.", type: "Discipline" },
  { text: "Trade ko tumhare paas aane do.", type: "Patience" },
  { text: "Trading decisions me emotions ka koi kaam nahi.", type: "Psychology" },
  { text: "Slowly build karo. Hamesha protect karo.", type: "Risk" },
  { text: "Har professional ek beginner tha jisne quit nahi kiya.", type: "Mindset" },
  { text: "Har trade se pehle apna checklist follow karo.", type: "Discipline" },
  { text: "Market har week opportunities se bhara hota hai.", type: "Patience" },
  { text: "Pride paise lose karwati hai. Humility paise banwati hai.", type: "Psychology" },
  { text: "Risk management hi asli trading skill hai.", type: "Risk" },
  { text: "Results slow hon tab bhi consistent raho.", type: "Mindset" },
  { text: "Stop out hona bade loss se better hai.", type: "Discipline" },
  { text: "Good traders rules ko money se zyada love karte hain.", type: "Psychology" },
  { text: "Har minute apna account check mat karo.", type: "Psychology" },
  { text: "Best revenge ek profitable account hota hai.", type: "Mindset" },
  { text: "Trading me patience power hai.", type: "Patience" },
  { text: "Sirf high probability setups par hi trade karo.", type: "Discipline" },
  { text: "Trading simple hai, lekin easy nahi.", type: "Mindset" },
  { text: "Jo control kar sakte ho usi par dhyan do. Baaki ignore karo.", type: "Psychology" },
  { text: "Losing trade me kabhi average down mat karo.", type: "Risk" },
  { text: "Winners har din seekhte rehte hain.", type: "Mindset" },
  { text: "Clear plan fear ko hata deta hai.", type: "Discipline" },
  { text: "Stock market impatient se patient logon me paisa transfer karne ki machine hai.", type: "Patience" },
  { text: "Feelings jhooth bolti hain. Charts sach batate hain.", type: "Psychology" },
  { text: "Size matter karti hai - jab sure na ho to chhota rakho.", type: "Risk" },
  { text: "Aaj ki discipline kal ki freedom banati hai.", type: "Discipline" },
  { text: "Great traders sabse pehle survival par focus karte hain.", type: "Mindset" },
  { text: "Plan ke hisaab se profit le lo.", type: "Discipline" },
  { text: "Losing bhi trading me jeet ka hissa hai.", type: "Psychology" },
  { text: "Paise risk karne se pehle apna edge ka wait karo.", type: "Patience" },
  { text: "Trading journal tumhara best teacher hai.", type: "Mindset" },
  { text: "Ek trade poore din ko decide nahi karna chahiye.", type: "Psychology" },
  { text: "Consistent small gains milkar wealth banati hain.", type: "Mindset" },
  { text: "Rules tumhe khud se protect karte hain.", type: "Discipline" },
  { text: "Market ko tumhari opinion ki parwah nahi hoti.", type: "Mindset" },
  { text: "Buy ya sell click karne se pehle saans lo.", type: "Psychology" },
  { text: "Risk kam lo. Seekho zyada.", type: "Risk" },
  { text: "Trading success self-control se start hoti hai.", type: "Discipline" },
  { text: "Pehle prepare karo, baad me trade karo.", type: "Patience" },
  { text: "Winners losers ko jaldi cut karte hain.", type: "Discipline" },
  { text: "Tumhari next trade tumhari best trade honi chahiye.", type: "Mindset" },
  { text: "Excitement ke liye trade mat karo.", type: "Psychology" },
  { text: "Safe chhota profit risky bade profit se better hai.", type: "Risk" },
  { text: "Chaos me calm raho.", type: "Psychology" },
  { text: "Trading me discipline freedom hai.", type: "Discipline" },
  { text: "Markets change hote hain. Tumhare rules nahi badalne chahiye.", type: "Mindset" },
  { text: "Patient trader impatient trader ka lunch kha jaata hai.", type: "Patience" },
  { text: "Losses ko bina emotion ke review karo.", type: "Psychology" },
  { text: "Logic se trade karo, ego se nahi.", type: "Mindset" },
  { text: "Stop loss tumhari insurance policy hai.", type: "Risk" },
  { text: "Chhota position, zyada peace of mind.", type: "Risk" },
  { text: "Har din apna plan follow karne ka mauka hai.", type: "Discipline" },
  { text: "Trading ek skill hai. Uski daily practice karo.", type: "Mindset" },
  { text: "Hot tips ignore karo. Apne analysis par trust karo.", type: "Discipline" },
  { text: "Best traders sabse patient hote hain.", type: "Patience" },
  { text: "Trend se kabhi fight mat karo.", type: "Mindset" },
  { text: "Achhi risk management ke liye tumhara account tumhara shukriya karega.", type: "Risk" },
  { text: "Objective raho. Emotions hatao.", type: "Psychology" },
  { text: "Har din 1% better hona bade success tak le jaata hai.", type: "Mindset" },
  { text: "No plan = gambling.", type: "Discipline" },
  { text: "Rules follow karne ko celebrate karo, sirf profit ko nahi.", type: "Psychology" },
  { text: "Market deta bhi hai aur le bhi leta hai. Dono ke liye ready raho.", type: "Mindset" },
  { text: "Doubt ho to haath baithao.", type: "Patience" },
  { text: "Good traders small lose karte hain. Bad traders big lose karte hain.", type: "Risk" },
  { text: "Discipline dreamers aur doers ke beech fark banati hai.", type: "Discipline" },
  { text: "Jeetne ke liye trade karo, right prove karne ke liye nahi.", type: "Psychology" },
  { text: "Simple rakho. Simple kaam karta hai.", type: "Mindset" },
  { text: "Thake hue ya distracted ho kar trade mat karo.", type: "Psychology" },
  { text: "Small wins se confidence build karo.", type: "Mindset" },
  { text: "Rule tab powerful hota hai jab tum usse follow karte ho.", type: "Discipline" },
  { text: "Jab tum patient hote ho tab time tumhara dost hota hai.", type: "Patience" },
  { text: "Risk wisely karo. Peace se so jao.", type: "Risk" },
  { text: "Kabhi kabhi jo trade tumne liya hi nahi, wahi best hota hai.", type: "Discipline" },
  { text: "Apne mind ko master karo, phir trading ko master kar loge.", type: "Psychology" },
  { text: "Sirf aaj ke trade par focus karo.", type: "Mindset" },
  { text: "Patience painful losses se bachati hai.", type: "Patience" },
  { text: "Plan ko aise follow karo jaise tumhari life uspe depend karti ho.", type: "Discipline" },
  { text: "Losses learning ki tuition fees hain.", type: "Psychology" },
  { text: "Consistent action consistent results laati hai.", type: "Mindset" },
  { text: "Saare eggs ek trade me mat daalo.", type: "Risk" },
  { text: "Disciplined trader dangerous hota hai.", type: "Discipline" },
  { text: "Market hamesha sikha raha hai. Kya tum sun rahe ho?", type: "Mindset" },
  { text: "Dekho. Wait karo. Phir act karo.", type: "Patience" },
  { text: "Emotions tumhe average banate hain. Discipline tumhe great banati hai.", type: "Psychology" },
  { text: "Capital ko aise protect karo jaise ye tumhari only chance ho.", type: "Risk" },
  { text: "Trading 90% wait aur 10% action hai.", type: "Patience" },
  { text: "Game me lambi der tak bano rahoge, to jeet jaoge.", type: "Mindset" },
  { text: "Rules amateurs par tumhari edge hain.", type: "Discipline" },
  { text: "Har trade ki zimmedari lo.", type: "Psychology" },
  { text: "Slow and steady trading race jeet ta hai.", type: "Mindset" },
  { text: "Loss ke baad risk kabhi mat badhao.", type: "Risk" },
  { text: "Calm trader zyada opportunities dekhta hai.", type: "Psychology" },
  { text: "Discipline daily practice hai.", type: "Discipline" },
  { text: "Confidence ke saath trade karo, arrogance ke saath nahi.", type: "Mindset" },
  { text: "Setup perfect hone tak wait karo.", type: "Patience" },
  { text: "Trading me sabse bada dushman tum khud ho.", type: "Psychology" },
  { text: "Chhote risks repeat karne se bade rewards milte hain.", type: "Risk" },
  { text: "Trade plan karo. Plan trade karo.", type: "Discipline" },
  { text: "Good traders lucky nahi hote, prepared hote hain.", type: "Mindset" },
  { text: "Fear ko saans ke saath bahar nikalo. Discipline ko andar lo.", type: "Psychology" },
  { text: "Market ki respect karo. Yeh tumse zyada purana hai.", type: "Mindset" },
  { text: "Patient traders ka secret weapon patience hoti hai.", type: "Patience" },
  { text: "Sirf bore hone ki wajah se trade mat karo.", type: "Psychology" },
  { text: "Sure na ho to kam risk lo.", type: "Risk" },
  { text: "Har winning trader ne bahut baar loss kiya hota hai.", type: "Mindset" },
  { text: "Discipline trading dreams ko reality me badal deti hai.", type: "Discipline" },
  { text: "Chart dekho, emotions nahi.", type: "Psychology" },
  { text: "Best traders sirf best setups hi lete hain.", type: "Discipline" },
  { text: "Knowledge ke liye hungry raho, execution me patient raho.", type: "Mindset" },
  { text: "Achha stop loss tumhara account bachata hai.", type: "Risk" },
  { text: "Trading business hai. Isse business ki tarah treat karo.", type: "Mindset" },
  { text: "Trend confirm hone ka wait karo.", type: "Patience" },
  { text: "Apni size control karo. Apne emotions control karo.", type: "Psychology" },
  { text: "Consistency trading ka asli holy grail hai.", type: "Mindset" },
  { text: "Sabse mushkil time me bhi rules follow karo.", type: "Discipline" },
  { text: "Markets wait karne walon ko reward karte hain.", type: "Patience" },
  { text: "Jab zarurat ho, side me rehna seekho.", type: "Psychology" },
  { text: "Kabhi revenge trade mat karo. Uske bajay walk away karo.", type: "Psychology" },
  { text: "Tumhari edge tumhari discipline me hai.", type: "Discipline" },
  { text: "Probabilities me socho, hopes me nahi.", type: "Mindset" },
  { text: "Small loss ek achha loss hota hai.", type: "Risk" },
  { text: "Machine ki tarah trade karo, insaan ki tarah socho.", type: "Psychology" },
  { text: "Jitna zyada wait karoge, utna better reward hoga.", type: "Patience" },
  { text: "Har din motivation se zyada discipline choose karo.", type: "Discipline" },
  { text: "Winners apne losses ko tiny rakhte hain.", type: "Risk" },
  { text: "Long term success par focus rakho.", type: "Mindset" },
  { text: "Ek win tumhe overconfident na bana de.", type: "Psychology" },
  { text: "Simple aur disciplined, complex aur emotional se better hai.", type: "Mindset" },
  { text: "Market har din open hota hai. Jaldi karne ki zarurat nahi.", type: "Patience" },
  { text: "Tumhara trading plan tumhara boss hai.", type: "Discipline" },
  { text: "Market jo deta hai use accept karo.", type: "Psychology" },
  { text: "Risk management self-love hai.", type: "Risk" },
  { text: "Trading me badi cheezein time leti hain.", type: "Patience" },
  { text: "Market ke student hamesha bane raho.", type: "Mindset" },
  { text: "Achhe aur bure dono time me apne system ko follow karo.", type: "Discipline" },
  { text: "Emotions trading ka sabse bada cost hain.", type: "Psychology" },
  { text: "Consistent hone tak chhota trade rakho.", type: "Risk" },
  { text: "Quiet traders sabse zyada paise kamate hain.", type: "Mindset" },
  { text: "Patience profitable hoti hai.", type: "Patience" },
  { text: "Aaj ka broken rule kal ki badi problem ban sakta hai.", type: "Discipline" },
  { text: "News par trade mat karo. Chart par trade karo.", type: "Mindset" },
  { text: "Dusre panic kar rahe hon tab cool raho.", type: "Psychology" },
  { text: "Ek achhi habit jo daily repeat hoti hai, sab kuch change kar deti hai.", type: "Mindset" },
  { text: "Tumhara stop loss non-negotiable hai.", type: "Risk" },
  { text: "Trading better decisions lene ka game hai.", type: "Psychology" },
  { text: "Discipline goals aur success ke beech ka bridge hai.", type: "Discipline" },
  { text: "Best traders gracefully lose karte hain.", type: "Psychology" },
  { text: "Money risk karne se pehle clarity ka wait karo.", type: "Patience" },
  { text: "Return pe nahi, return per risk pe focus karo.", type: "Risk" },
  { text: "Seekhte raho. Improve karte raho. Jeette raho.", type: "Mindset" },
  { text: "No emotions. Sirf execution.", type: "Discipline" },
  { text: "Market tumhara wait kar sakta hai.", type: "Patience" },
  { text: "Small consistent effort kabhi-kabhi big effort se better hota hai.", type: "Mindset" },
  { text: "Apni capital ko aise protect karo jaise ek maa apne bachche ko karti hai.", type: "Risk" },
  { text: "Bada loss na hone dena hi jeet hai.", type: "Psychology" },
  { text: "Sirf tab trade karo jab sab kuch line up ho.", type: "Discipline" },
  { text: "Trading success ek long game hai.", type: "Mindset" },
  { text: "Fear normal hai. Fear par act karna expensive hai.", type: "Psychology" },
  { text: "Discipline aaj. Wealth kal.", type: "Discipline" },
  { text: "Patient trader hamesha end me jeet ta hai.", type: "Patience" },
  { text: "Review karo. Seekho. Improve karo. Repeat karo.", type: "Mindset" },
  { text: "Kabhi ek trade par poora farm mat laga do.", type: "Risk" },
  { text: "Achha trader calm trader hota hai.", type: "Psychology" },
  { text: "Rules follow karo. Profits collect karo.", type: "Discipline" },
  { text: "Trading un logon ko reward karti hai jo risk ki respect karte hain.", type: "Risk" },
  { text: "Humble raho. Hungry raho. Disciplined raho.", type: "Mindset" },
  { text: "Best setup wait ke laayak hota hai.", type: "Patience" },
  { text: "Tumhara mind tumhara sabse powerful trading tool hai.", type: "Psychology" },
  { text: "Trading me consistency king hai.", type: "Mindset" },
  { text: "Losses cut karo. Winners ride karo. Repeat karo.", type: "Discipline" },
  { text: "Trades force mat karo. Unhe hone do.", type: "Patience" },
  { text: "Trading simple hai: rules follow karo aur risk manage karo.", type: "Mindset" },
  { text: "A disciplined mind ko defeat nahi kiya ja sakta.", type: "Psychology" },
  { text: "Risk smart. Trade smart. Win smart.", type: "Risk" },
  { text: "Har din jab tum apna plan follow karte ho, woh winning day hota hai.", type: "Discipline" },
  { text: "Market patient hai. Tumhe bhi patient hona chahiye.", type: "Patience" },
  { text: "Winners is baat par focus karte hain ki kya right hai, na ki kaun right hai.", type: "Mindset" },
  { text: "Hamesha control me raho.", type: "Psychology" },
  { text: "Discipline har trading success ki foundation hai.", type: "Discipline" },
  { text: "Trade kam karo. Study zyada karo. Earn zyada karo.", type: "Mindset" },
  { text: "Kabhi hope ko apne stop loss ki jagah mat do.", type: "Risk" },
  { text: "Calm mind best trades dekhta hai.", type: "Psychology" },
  { text: "Patience ke saath apni trading muscle build karo.", type: "Patience" },
  { text: "Profitable trading tak ka raasta discipline se banta hai.", type: "Discipline" },
  { text: "Process par trust karo. Khud par trust karo.", type: "Mindset" },
  { text: "Achhi risk management = lambi trading career.", type: "Risk" },
  { text: "Wait ko embrace karo. Woh achha pay karta hai.", type: "Patience" },
  { text: "Trading psychology hi real game hai.", type: "Psychology" },
  { text: "Discipline beginners ko professionals me badal deti hai.", type: "Discipline" },
  { text: "Best traders sabse boring hote hain.", type: "Mindset" },
  { text: "Risk control karo. Profits ko surprise banne do.", type: "Risk" },
  { text: "Present me raho. Abhi ko trade karo.", type: "Psychology" },
  { text: "Patience tumhara silent profit partner hai.", type: "Patience" },
  { text: "Aaj rules follow karo, kal bigger account milega.", type: "Discipline" },
  { text: "Trading character ka test hai.", type: "Mindset" },
  { text: "Kabhi gusse me trade mat karo. Kabhi desperate hoke trade mat karo.", type: "Psychology" },
  { text: "Chhoti position sizes tumhe game me rakhti hain.", type: "Risk" },
  { text: "Disciplined trader hamesha aur strong hokar lautta hai.", type: "Discipline" },
  { text: "Markets move karte hain. Tumhare rules same rehte hain.", type: "Mindset" },
  { text: "Hunter ki tarah wait karo. Pro ki tarah strike karo.", type: "Patience" },
  { text: "Tumhara trading journal kabhi jhooth nahi bolta.", type: "Psychology" },
  { text: "Discipline long-term success ko short-term fun par choose karna hai.", type: "Discipline" },
  { text: "Selective bano. Profitable bano.", type: "Mindset" },
  { text: "Risk sirf 1% lo. Baby ki tarah so jao.", type: "Risk" },
  { text: "Patient trader hi wealthy trader hota hai.", type: "Patience" },
  { text: "Apni emotions par control lao. Market par control lao.", type: "Psychology" },
  { text: "Har rule follow karna money earn karna hai.", type: "Discipline" },
  { text: "Trading success consistent logon ki hoti hai.", type: "Mindset" },
  { text: "Jab market clear na ho, tab side me raho.", type: "Patience" },
  { text: "Capital protect karo. Baaki sab follow karega.", type: "Risk" },
  { text: "Best traders achha lose karte hain.", type: "Psychology" },
  { text: "Discipline tumhari superpower hai.", type: "Discipline" },
  { text: "Long term socho. Short term trade karo.", type: "Mindset" },
  { text: "Patience trading me dividends deti hai.", type: "Patience" },
  { text: "Khud ko control karo. Apne results ko control karo.", type: "Psychology" },
  { text: "Ek achha trader patient, disciplined aur calm hota hai.", type: "Mindset" },
  { text: "Pehle rules. Baad me profits.", type: "Discipline" },
  { text: "Kabhi chase mat karo. Hamesha plan karo.", type: "Mindset" },
  { text: "Market disciplined logon ke liye generous hota hai.", type: "Discipline" },
  { text: "Calm raho aur apna plan follow karo.", type: "Psychology" },
  { text: "Chhota risk. Badi patience. Bada reward.", type: "Patience" },
  { text: "Emotions hata do to trading easy ho jaati hai.", type: "Psychology" },
  { text: "Discipline aaj. Kal celebrate karo.", type: "Discipline" },
  { text: "Patient hamesha end me jeette hain.", type: "Patience" },
  { text: "Agar disciplined raho to tumhare best days aage hain.", type: "Mindset" },
  { text: "Risk smart. Trade calm. Win big.", type: "Risk" },
  { text: "Plan follow karo. Process par trust karo.", type: "Discipline" }
];

export default function DailyQuote({ lang }) {
  const [quote, setQuote] = useState({ text: "", type: "" });

  useEffect(() => {
  const now = new Date();
  const day = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);

  const source = lang === "EN" ? quotesEN : quotesHN;
  setQuote(source[day % source.length]);
}, [lang]);

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="p-6 rounded-2xl border border-[var(--border)] bg-[var(--card)] backdrop-blur-sm relative overflow-hidden group"
    >
      <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
        <Quote size={60} />
      </div>
      <div className="flex items-center gap-2 mb-3">
        <Lightbulb size={14} className="text-[var(--primary)]" />
        <span className="text-[10px] uppercase tracking-[0.2em] font-bold text-gray-500">{quote.type} Wisdom</span>
      </div>
      <AnimatePresence mode="wait">
  <motion.p
    key={quote.text}
    initial={{ opacity: 0, y: 10 }}
    animate={{ opacity: 1, y: 0 }}
    exit={{ opacity: 0, y: -10 }}
    transition={{ duration: 0.35 }}
    className="text-xl font-medium text-[var(--text)] leading-relaxed italic"
  >
    “{quote.text}”
  </motion.p>
</AnimatePresence>
    </motion.div>
  );
}